import PyInstaller.__main__

PyInstaller.__main__.run([
    "hero-siege-stats.py",
    "--onefile", "--windowed",
    "--name", "HeroSiegeStats",
    "--icon", "assets/icons/logo.ico",
    "--add-data", "assets;assets/",
    "--add-data", "src;src/",
    "--collect-all", "scapy",
    "--collect-all", "psutil",
    "--hidden-import", "scapy.all",
    "--hidden-import", "scapy.layers.all",
    "--hidden-import", "scapy.layers.inet",
    "--hidden-import", "scapy.sendrecv",
    "--hidden-import", "scapy.arch",
    "--hidden-import", "scapy.arch.windows",
    "--hidden-import", "scapy.arch.windows.native",
    "--hidden-import", "src.utils.single_instance",
    "--hidden-import", "src.utils.config",
    "--hidden-import", "src.utils.sound",
    "--hidden-import", "src.utils.session_saver",
    "--hidden-import", "src.consts.i18n",
    "--hidden-import", "src.consts.classes",
    "--hidden-import", "src.consts.satanic_buffs",
    "--hidden-import", "src.models.stats.drop_log",
    "--hidden-import", "src.models.stats.zone_stats",
    "--hidden-import", "src.models.stats.account",
    "--hidden-import", "src.gui.components.zone_panel",
    "--hidden-import", "src.gui.components.collapsible",
    "--hidden-import", "src.gui.components.progress_panel",
    "--hidden-import", "src.gui.windows.drop_log_window",
    "--hidden-import", "src.gui.windows.zone_window",
    "--hidden-import", "src.gui.windows.settings_window",
    "--hidden-import", "src.gui.windows.faq_window",
    "--hidden-import", "src.gui.widgets.toast",
    "--clean", "--noconfirm",
])
